# Generated by Django 4.0.3 on 2024-01-20 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_user'),
        ('carts', '0002_alter_cart_user'),
        ('users', '0002_user_delete_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
