# Generated by Django 4.0.3 on 2024-01-20 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cartItems',
            new_name='cart_items',
        ),
    ]
